### PR TITLE
feat: adds requirements and settings for the redis event bus

### PR DESCRIPTION
**Pull request by pomegranited**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by bmtcril** [comment]
Thanks for this, and reminding me that this repo exists. 😬 I'm hoping we can move this repo to encapsulate both Kafka and redis backends, so am doing investigation for that work in #5 . I'm going to roll this awesome work into that for now and we'll see which way it goes.

**Comment by pomegranited** [comment]
Thanks @bmtcril ! I'll close this PR then.

**Comment by openedx-webhooks** [comment]
@pomegranited Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-event-bus-redis&entry.867055334=https://github.com/openedx/tutor-contrib-event-bus-redis/pull/4&entry.1484655318=https://github.com/pomegranited&entry.752974735=2024-02-02+04:46&entry.1917517419=2024-02-12+23:03&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
